apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: d3c4d4nc3/fastapi_demo:979e568b8745ee622d52b5cbf4d758d83a2ff677
        ports:
        - containerPort: 8000

