apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: d3c4d4nc3/fastapi_demo:5372f9aa7058e9ed0af2fc132deeab41ec82b56d
        ports:
        - containerPort: 8000

