name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=d3c4d4nc3/fastapi_demo:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Update deployment.yml with new image
        run: |
          chmod +x scripts/update_k8s_image.sh
          ./scripts/update_k8s_image.sh ${{ env.IMAGE_NAME }}

      - name: Push commit back to repo
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main

  deploy-to-k8s:
    needs: docker-build-push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Set up kubectl
      #  uses: azure/setup-kubectl@v3
      #  with:
      #    version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: Verify pods and services
        run: |
          kubectl get pods -o wide
          kubectl get svc -o wide

      # Для Minikube: получить URL сервиса (шаг сработает только на self-hosted раннере, где установлен minikube)
      - name: Get service URL (Minikube)
        run: |
          minikube service my-app-service –url
